name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm install

      - name: Install playwright
        run: npx playwright install

      - name: Run jest tests
        run: npm run jest

      - name: Build application server
        run: npm run build

      - name: Start application server
        run: npm start &

      - name: Start mock server
        run: cd IskingInCheckContract && npm install && npm run mock &

      - name: Wait for servers to be ready
        run: sleep 10 # Adjust the sleep time based on your servers' startup time

      - name: Run cucumber tests
        run: npm run cucumber

      # # KILL ALL SERVERS
      # - name: Kill all node processes
      #   run: killall node

      - name: Build Docker image
        run: docker build -t iskinginchecknext:${{ github.sha }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push iskinginchecknext:${{ github.sha }}

      - name: Print a sarcastic joke
        run: echo "Why did Darth Vader invade the chessboard? Because he heard the Knight was powerful, but found out it could only move in an L shape. Not so impressive for the Dark Side."
